UrlShortener/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^urlsh/', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

app/urls.py
from django.conf.urls import url

from . import views

app_name = 'app'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<alias_id>[0-9]+)/$', views.detail, name='detail'),
]

app/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Alias(models.Model):
    url = models.CharField(max_length=200)
    alias = models.CharField(max_length=20)
    alias_date = models.DateTimeField(default=datetime.now, blank=True)
    alias_name = models.CharField(max_length=501)
    alias_description = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = "aliases"

app/views.py
from django.http import HttpResponse
from django.views import generic

from .models import Alias

# Create your views here.


class IndexView(generic.ListView):
    template_name = 'app/index.html'
    context_object_name = 'alias_list'

    def get_queryset(self):
        return Alias.objects.all


def detail(request, alias_id):
    return HttpResponse("You're looking at alias %s." % alias_id)

templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{#    <link rel="stylesheet" type="text/css" href="{% static 'pollsApp/style.css' %}"/>#}
    <title>Url Shortener App</title>
</head>
<body>
    {% if alias_list %}
        <ul>
        {%  for alias in alias_list %}
            <li><a href="{% url 'app:detail' alias.id %}">{{ alias.alias_name }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
    <p> No aliases are available. </p>
    {%  endif %}
</body>
</html>